### ISSUE TITLE
ERROR: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by demiro** [arilotter/icon-convert#1]
when running commands to convert either svg or png to ico, I get this error

> (node:25192) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'filter' of undefined
    at C:\WORK\YE-WE-DO\node_modules\icon-convert\index.js:76:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:25192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am running it like this:
`npx icon-convert -t ico -o icons favicon64x64.png`
`npx icon-convert -t ico -o icons favicon.svg`

I am running it on windows, node version 12.11.0

**Comment by demiro** [comment]
also, your online converter is producing error as well

**Comment by lutzroeder** [comment]
@arilotter can you provide some context? What would be needed to fix this issue and update the package?

**Comment by ethernet8023** [comment]
Hey @demiro ! I don't run the online converter, this package is simply a wrapper around their API. I tested a few files and I'm getting an error too, so it looks like the https://iconverticons.com/ online service is broken. You should submit a support request here: https://iconverticons.com/support/
( cc @lutzroeder )

**Comment by lutzroeder** [comment]
@demiro, @arilotter can you close this issue or untag me? The website is no longer available so it's unlikely this will get fixed.
